[package]
name = "atomic_swap"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = { version = "26.0.1", features = ["alloc"] }

[dev-dependencies]
soroban-sdk = { version = "26.0.1", features = ["testutils"] }
proptest = { version = "1", default-features = false, features = ["std"] }
ed25519-dalek = "2"
